const adatok=[
    {orszag:'Norvégia',fovaros:'Oslo'},
    {orszag:'Svédország',fovaros:'Stockholm'},
    {orszag:'Finnország',fovaros:'Helsinki'},
    {orszag:'Dánia',fovaros:'Koppenhága'},
    {orszag:'Izland',fovaros:'Reykjavík'},
    {orszag:'Nagy Britannia',fovaros:'London'},
    {orszag:'Írország',fovaros:'Dublin'},
    {orszag:'Franciaország',fovaros:'Párizs'},
    {orszag:'Belgium',fovaros:'Brüsszel'},
    {orszag:'Hollandia',fovaros:'Amszterdam'},
    {orszag:'Luxemburg',fovaros:'Luxembourg'},
    {orszag:'Portugália',fovaros:'Lisszabon'},
    {orszag:'Spanyolország',fovaros:'Madrid'},
    {orszag:'Olaszország',fovaros:'Róma'},
    {orszag:'Szlovénia',fovaros:'Ljubljana'},
    {orszag:'Horvátország',fovaros:'Zágráb'},
    {orszag:'Szerbia',fovaros:'Belgrád'},
    {orszag:'Montenegró',fovaros:'Podgorica'},
    {orszag:'Bosznia Hercegovina',fovaros:'Szarajevó'},
    {orszag:'Macedónia',fovaros:'Skopje'},
    {orszag:'Kosovo ',fovaros:' Pristina'},
    {orszag:'Albánia',fovaros:'Tirana'},
    {orszag:'Bulgária',fovaros:'Szófia'},
    {orszag:'Görögország',fovaros:'Athén'},
    {orszag:'Észtország',fovaros:'Tallinn'},
    {orszag:'Lettország',fovaros:'Riga'},
    {orszag:'Litvánia',fovaros:'Vilnius'},
    {orszag:'Románia',fovaros:'Bukarest'},
    {orszag:'Moldova',fovaros:'Kisinyov'},
    {orszag:'Oroszország',fovaros:'Moszkva'},
    {orszag:'Ukrajna',fovaros:'Kijev'},
    {orszag:'Belorusszia',fovaros:'Minszk'},
    {orszag:'Németország',fovaros:'Berlin'},
    {orszag:'Svájc',fovaros:'Bern'},
    {orszag:'Ausztria',fovaros:'Bécs'},
    {orszag:'Csehország',fovaros:'Prága'},
    {orszag:'Lengyelország',fovaros:'Varsó'},
    {orszag:'Szlovákia',fovaros:'Pozsony'},
    {orszag:'Magyarország',fovaros:'Budapest'},
    {orszag:'Ciprus',fovaros:'Nicosia'},
    {orszag:'Málta',fovaros:'La Valetta'},
    {orszag:'Monaco',fovaros:'Monaco'},
    {orszag:'San Marino',fovaros:'San Marino'},
    {orszag:'Andorra',fovaros:'Andorra la Vella'},
    {orszag:'Liechtenstein',fovaros:'Vaduz'}
]